### ISSUE TITLE
[Ask] Install in rails 4

### ISSUE THREAD

**Issue by microdevil** [chrahunt/docx#15]
Dear all

I am new developer in rails.
Could i install this gem in rails 4 ?
I have put it in Gemfile. when i bundle install, i get the issues that my rubyzip is not compitible. this is my message error
In Gemfile:
    docx (>= 0) ruby depends on
      rubyzip (~> 0.9) ruby

```
roo (>= 0) ruby depends on
  rubyzip (1.1.0)
```

Please let me know about my problem
Sory for my bad english.
Thanks

**Comment by 9teen90nine** [comment]
Hi! I am experiencing the same problem, as many gems require rubyzip > 1.0, and I can't use this gem. Is there any chance this could be fixed?

**Comment by andyw8** [comment]
@9teen90nine which version of the gem are you using?

**Comment by 9teen90nine** [comment]
I tried the latest version available, but i switched to rubyzip+nokogiri and actually do not need it anymore.

**Comment by mebibou** [comment]
Otherwise you could run `bundle update` and it should work, resolved it for me

**Comment by chrahunt** [comment]
We've used a more recent version of rubyzip for several years so this should no longer be an issue.
