### ISSUE TITLE
How to use docx gem with s3 files 

### ISSUE THREAD

**Issue by the7oka** [chrahunt/docx#36]
I have this create action to extract data from doc and docx files (if available) using the docx gem and the msworddoc-extractor gem

  ```
 if @subject.save
    if @subject.odoc.present?
      @odoc_url = @subject.odoc.url
      if File.extname(URI.parse(@odoc_url).path) == ".docx"
        @subject.homework= ""
        doc = Docx::Document.open(@odoc_url)
        doc.paragraphs.each do |p|
          @subject.homework = @subject.homework+p.to_html
        end
      else
        MSWordDoc::Extractor.load(@odoc_url) do |doc|
          @subject.homework= doc.whole_contents
        end
      end
      @subject.save
    end
```
now, doc files works fine.. My problem is with `doc = Docx::Document.open(@odoc_url)` when i use the code on my local machine it works fine.. when i push into production i get an error `Zip::Error: File s3.amazonaws.com/~~~ not found` I'm not really sure how to load the file to be accessible to the docx gem

**Comment by KINGSABRI** [comment]
did you install `rubyzip` gem? 
Note: `docx` uses older version of `rubyzip` which conflict with newer one. I clone `docx` gem then update `rubyzip` version to newer version from `docx.gemspec` then 
```
gem build docx.gemspec
```

**Comment by chrahunt** [comment]
You must download the document locally before attempting to process it with this gem, we do not support arbitrary URLs.

**Comment by fercreek** [comment]
@the7oka did you solve this in another way¿

**Comment by the7oka** [comment]
@fercreek that was a very old project. i had to dig around a little bit.
but it's really my mistake since i should've posted the answer when i got it done.

anyways, just run `doc = Docx::Document.open(open(@odoc_url).path)` instead of `doc = Docx::Document.open(@odoc_url)`
so basically you don't open the url directly. instead, you open the file itself. @chrahunt suggested that in his words but being the noob i was back then, i didn't understand how to implement it right away. 
now i'm not sure why nobody suggested that exact peace of code. but i'm pretty sure this works since my old code is still running as we speak.
cheers and thanks for bring me back to the noob me :)

**Comment by fercreek** [comment]
@the7oka thank you a lot! It works to me!
