### ISSUE TITLE
Update TOC

### ISSUE THREAD

**Issue by giper45** [chrahunt/docx#44]
Hi, I'm looking for a library that does a simple task:
- Open a word document,
- Update all tables, graphs and table of contents. 
Is docx able to do this task? 

Thanks in advance

**Comment by chrahunt** [comment]
This library provides some convenience functions for iterating over tables, but graphs and TOC sections will need to be extracted and edited using the underlying [Nokogiri](https://nokogiri.org/) interface on the relevant nodes. I would suggest taking a docx that has the content types you want to interact with then explore it, incrementally collecting the xpath expressions you'll need to select the nodes you're interested in.
