### ISSUE TITLE
Can we fetch Page Number while reading the docx?

### ISSUE THREAD

**Issue by rajdevofrails** [chrahunt/docx#60]
Hi, folks!

Is there a way to fetch the page number of docx file while reading them.

**Comment by chrahunt** [comment]
Check out the [advanced](https://github.com/chrahunt/docx#advanced) section in the README which details how you can specify arbitrary xpath expressions to read and iterate over nodes contained in the document. For specific information on what nodes in the docx document should be used to get e.g. the page numbers, stackoverflow would be a more appropriate forum.

**Comment by pickhardt** [comment]
Correct me if I'm wrong but I actually don't think that a paragraph has page number(s) associated with its nodes data. I just checked and read up on it but it looks like docx files are not inherently paged; their layout depends on the rendering application and various factors like font size, margins, etc. Unfortunately I don't see an easy way to get page number data for a given paragraph object.
