### ISSUE TITLE
Aligned images breaks the docx file

### ISSUE THREAD

**Issue by echan00** [chrahunt/docx#63]
After numerous testing of a document that won't open when saved with this gem, I've been able to pinpoint that a docx containing an aligned image will break after saving.

Here is an example docx with just one aligned image:
[www.docx](https://github.com/chrahunt/docx/files/2911425/www.docx)

Here is the resulting docx when saved with this gem: 
[www-broken.docx](https://github.com/chrahunt/docx/files/2911424/www-broken.docx)

**Comment by chrahunt** [comment]
Can you please provide the code that takes the example as input and generates the broken file?

**Comment by echan00** [comment]
Sorry about this @chrahunt, after further debugging, I found that the issue not related to this gem. 

Thank you again for supporting this gem, its very helpful
