### ISSUE TITLE
[Question] Some question about the gem

### ISSUE THREAD

**Issue by tan-wei** [chrahunt/docx#74]
`docx` is the most popular gem which can manipulate `docx` documents. However, I have some questions which is not described in the document.

1. Must we use a valid existed `docx` to read or write?
  - The answer probably "YES" though some issues in the repo
2. Can we insert tables just including texts?

**Comment by misdoro** [comment]
To answer Q2: you may insert rows in existing tables, first you find the row that interests you, then you may insert a copy like `row.copy.insert_after(row)`

**Comment by tan-wei** [comment]
Got it. Thanks!
